version: '3'
services:
  web-server:
    build: ./web-server
    ports:
      - '8080:80'
      - '4430:443'
    depends_on:
      - app
    volumes:
      - ./web-server/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/public/:/var/www/html/

  app:
    build:
      context: ./app
      args:
        HOST_GID: $HOST_GID
        HOST_UID: $HOST_UID
    depends_on:
      - db
    links:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
    env_file:
      - .env
    volumes:
      - ./app/public/:/var/www/html/
      - ./app/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  db:
    image: mysql:5.7
    ports:
      - '3307:3306'
    env_file:
      - .env
    volumes:
      - ./db/data/:/var/lib/mysql/
