version: '3'
services:
  web-server:
    build: ./web-server
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
    volumes:
      - ./web-server/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/html:/var/www/html

  app:
    build: ./app
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
    env_file:
      - .env
    volumes:
      - ./data/html:/var/www/html
      - ./app/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  db:
    image: mysql:5.7
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/mysql
